# Use the lastest version of circleCi pipeline process engine
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcomme-orb
  welcome: circleci/welcome-orb@0.4.1

# jobs to be run
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
# Orchestrate or schedule a set of job
workflows:
  # Name of the workflow "welcome"
  welcome:
    # run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello
