# making use of env variables
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Echo an env var is part of this project"
          command:  |
            echo $MY_NAME
workflows: